// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _cal from "./cal";
export type $UserλShape = $.typeutil.flatten<_std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5fλShape & {
  "username": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "inserted_at": $.PropertyDesc<_cal.$local_datetime, $.Cardinality.One, false, false, false, true>;
  "password_hash": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "updated_at": $.PropertyDesc<_cal.$local_datetime, $.Cardinality.One, false, false, false, true>;
  "email": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5f['__exclusives__'],
  {username: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {email: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $User = $.makeType<$User>(_.spec, "b3ec3a72-333f-11ee-a5d6-ffc7de6778d4", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { $User, User };

type __defaultExports = {
  "User": typeof User
};
const __defaultExports: __defaultExports = {
  "User": User
};
export default __defaultExports;
